name: tkd_terms
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flip_card: ^0.6.0
  flutter_animator: ^3.2.0
  get: ^4.3.8
  percent_indicator: ^3.4.0
  pull_to_refresh: ^2.0.0
  yaml: ^3.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cards.json
    - assets/cards.yaml
